name: orange_player
description: "A new Flutter project."

# Prevent accidental publishing to pub.dev.
publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ">=3.2.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter

  on_audio_query: ^2.9.0
  permission_handler: ^11.1.0
  provider: ^6.1.1
  just_audio: ^0.9.36
  just_audio_mpv: ^0.1.7
  shared_preferences: ^2.2.2
  google_fonts: ^6.1.0
  audio_video_progress_bar: ^2.0.1
  just_audio_background: ^0.0.1-beta.11

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true

  # Enable generation of localized Strings from arb files.
  generate: true

  assets:
    # Add assets from the images directory to the application.
    - assets/images/
